name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Compile
      id: compile
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Compile
        setup-command: ''
        command: g++ -std=c++17 -Wall -Werror lab-1-part-b.cpp Student.cpp -o main
        timeout: 10
        max-score: 5
    - name: Make check.sh executable
      run: chmod +x check.sh
    - name: All students present
      id: all-students-present
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: All students present
        command: ./check.sh
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        COMPILE_RESULTS: "${{steps.compile.outputs.result}}"
        ALL-STUDENTS-PRESENT_RESULTS: "${{steps.all-students-present.outputs.result}}"
      with:
        runners: compile,all-students-present